---
title: "Black Hole-New-World"
author: "Jerad Steven Acosta"
date: 2019-12-23
categories: ["Cool Talk", "Ideas"]
tags: ["Black Hole","Space","Physics"]
---

## Big Bag to Big Freeze  

As our universe presses on past 13.5 billion years, age gets the best of it. The ever accelerating expansion, dark energy and dark matter press us toward a big freeze.  

Eventually, the growing source behind the force that visibly expands our galaxy apart from each other will press and press at our atomic particles until they can no longer maintain the structure we require for life and the physical universe as we know it.  


## Black Hole-New-World

As we face complete entropy in the static frozen void, we seek into another deep abyss for salvation.  

A last ditch effort for the comforting home to our future descendants is found in the almighty black hole that used to strike fear in inter galactic travelers across the multiverse.  



Black hole forms with new smaller Big Bang. More dense than current universe. Perhaps different structure for matter.


## Ethics of Reality Birthing  

Bubbling a universe into existance for recording and measurements.  
Running experiments off entire realities, chasing disolution from inception.  

Can we make life and a universe in a tiny black hole in a laboratory?  

What are the ethics to playing god at that level?  

Perhaps creating an entire universe and its history then destroying it, just before breaking for holiday.  

Then repeating the same experiment over and over and over... ?  